jobs:
  - name: runSh-1_1
    type: runSh
    steps:
      # - IN: sample-script-2
      - IN: trigger-dv-man-1_1
      - TASK:
        - script: sleep 1
    on_success:
      # - uname -a
      - script: echo "this works"
    on_failure:
      # - uname -a
      - script: echo "Inside on failure"

  - name: runSh-2_1
    type: runSh
    steps:
      # - IN: sample-script-2
      - IN: runSh-1_1
      - IN: trigger-dv-man-1_1
      - TASK:
        - script: sleep 1
    on_success:
      # - uname -a
      - script: echo "this works"
    on_failure:
      # - uname -a
      - script: echo "Inside on failure"

  - name: runSh-3_1
    type: runSh
    allowPublicAccess: true
    steps:
      # - IN: sample-script-2
      - IN: runSh-1_1
      - IN: runSh-2_1
      - IN: trigger-dv-man-1_1
      - IN: trigger-dv-man-2_1
      - TASK:
        - script: echo "*************** In Tasks *************"
        - script: sleep 15
        - script: echo $JOB_STATE
        - script: ls
        - script: echo "versionName=satble" >> $JOB_STATE/runSh-3_1.env;
        - script: echo "API_URL=0.0.0.0" >> $JOB_STATE/runSh-3_1.env
        - script: echo "VAR_A=1" >> $JOB_STATE/runSh-3_1.env
    on_success:
      # - uname -a
      - script: echo "this works"
    on_failure:
      # - uname -a
      - script: echo "Inside on failure"

  # - name: dv-man
  #   type: manifest
  #   steps:
  #     - IN: dv-image
  #     #   pull: true
  #     # - IN: dockOutImage
  #     # - IN: dv-params
  #     # - IN: dv-gitRepo
  #     # - IN: trigger-dv-man-2
  #     - IN: trigger-dv-man-1
  #       # applyTo:
  #       #   - dv-image
  #     - TASK: managed
  #     # - OUT: dv-gitRepoOut
  #     # - OUT: dv-image-1
  #   on_success:
  #     - echo "this is on_success step of dv-man of type manifest"
  #   on_failure:
  #     - echo "this is on_failure step of dv-man of type manifest"

  # - name: dv-man-2
  #   type: manifest
  #   steps:
  #     - IN: dv-man
  #     #   pull: true
  #     # - IN: dockOutImage
  #     # - IN: dv-params
  #     # - IN: dv-gitRepo
  #     # - IN: trigger-dv-man-2
  #     - IN: trigger-dv-man-1
  #       # applyTo:
  #       #   - dv-image
  #     - TASK: managed
  #     # - OUT: dv-gitRepoOut
  #     # - OUT: dv-image-1
  #   on_success:
  #     - echo "this is on_success step of dv-man of type manifest"
  #   on_failure:
  #     - echo "this is on_failure step of dv-man of type manifest"

  # - name: dv-man-3
  #   type: manifest
  #   steps:
  #     - IN: dv-man-2
  #     #   pull: true
  #     # - IN: dockOutImage
  #     # - IN: dv-params
  #     # - IN: dv-gitRepo
  #     # - IN: trigger-dv-man-2
  #     - IN: trigger-dv-man-1
  #       # applyTo:
  #       #   - dv-image
  #     - TASK: managed
  #     # - OUT: dv-gitRepoOut
  #     # - OUT: dv-image-1
  #   on_success:
  #     - echo "this is on_success step of dv-man of type manifest"
  #   on_failure:
  #     - echo "this is on_failure step of dv-man of type manifest"

  # - name: dv-man-1
  #   type: manifest
  #   steps:
  #     # - IN: dv-image-6
  #     # - IN: dv-image-2
  #     # - IN: dv-image-3
  #     # - IN : trigger-dv-man-2
  #     - IN: dv-image
  #       pull: true
  #     # - IN: dv-opts
  #     # - IN: dv-params
  #     # - IN: dv-gitRepo
  #     # - IN: trigger-dv-man-1
  #       # applyTo:
  #       #   - dv-image
  #     - TASK: managed
  #     # - OUT: dv-gitRepoOut
  #     # - OUT: dv-image-4
  #     # - OUT: dockOutImage
  #   on_success:
  #     - echo 'this is on_success step of dv-man of type manifest'
  #   on_failure:
  #     - echo 'this is on_failure step of dv-man of type manifest'

  # - name: dv-man-2
  #   type: manifest
  #   steps:
  #     # - IN: dv-image
  #     #   pull: true
  #     # - IN: dockInImage
  #     - IN: dv-man-1
  #     # - IN: dv-params
  #     # - IN: dv-gitRepo
  #     # - IN: trigger-dv-man-2
  #     # - IN: trigger-dv-man-1
  #       # applyTo:
  #       #   - dv-image
  #     - TASK: managed
  #     # - OUT: dv-gitRepoOut
  #     # - OUT: dv-image-1
  #   on_success:
  #     - echo "this is on_success step of dv-man of type manifest"
  #   on_failure:
  #     - echo "this is on_failure step of dv-man of type manifest"

  # - name: dv-man-3
  #   type: manifest
  #   steps:
  #     # - IN: dv-image
  #     #   pull: true
  #     # - IN: dockInImage
  #     - IN: dv-man-2
  #     # - IN: dv-man
  #     # - IN: dv-params
  #     # - IN: dv-gitRepo
  #     # - IN: trigger-dv-man-2
  #     # - IN: trigger-dv-man-1
  #       # applyTo:
  #       #   - dv-image
  #     - TASK: managed
  #     # - OUT: dv-gitRepoOut
  #     # - OUT: dv-image-1
  #   on_success:
  #     - echo "this is on_success step of dv-man of type manifest"
  #   on_failure:
  #     - echo "this is on_failure step of dv-man of type manifest"

  # - name: dv-man-4
  #   type: manifest
  #   steps:
  #     # - IN: dv-image
  #     #   pull: true
  #     # - IN: dockInImage
  #     # - IN: dv-man
  #     # - IN: dv-man-1
  #     # - IN: dv-man-2
  #     - IN: dv-man-3
  #     # - IN: dv-params
  #     # - IN: dv-gitRepo
  #     # - IN: trigger-dv-man-2
  #     # - IN: trigger-dv-man-1
  #       # applyTo:
  #       #   - dv-image
  #     - TASK: managed
  #     # - OUT: dv-gitRepoOut
  #     # - OUT: dv-image-1
  #   on_success:
  #     - echo "this is on_success step of dv-man of type manifest"
  #   on_failure:
  #     - echo "this is on_failure step of dv-man of type manifest"

# #   - name: dv-man-versionName
# #     type: manifest
# #     steps:
# #       - IN: dv-image
# #         pull: false
# #         versionName: latest
# #       - IN: dv-opts
# #       - IN: dv-params
# #         applyTo:
# #           - dv-image
# #       - TASK: managed
# #       - IN: trigger-dv-man

# #   - name: dv-man-versionNumber
# #     type: manifest
# #     steps:
# #       - IN: dv-image
# #         pull: false
# #         versionNumber: 1
# #       - IN: dv-opts
# #       - IN: dv-params
# #         applyTo:
# #           - dv-image
# #       - TASK: managed
# #       - IN: trigger-dv-man

# #   - name: dv-test
# #     type: deploy
# #     on_start:
# #       - NOTIFY: slackNotification
# #     steps:
# #       - IN: dv-man
# #       - IN: env-test
# #       - TASK: managed
# #         deployMethod: upgrade
# #     on_success:
# #       - NOTIFY: slackNotifcation
# #     on_failure:
# #       - NOTIFY: slackNotification

# #   - name: box-man
# #     type: manifest
# #     steps:
# #       - IN: box-image
# #         pull: false
# #       - IN: box-opts
# #       - IN: box-params
# #       - TASK: managed

# #   - name: box-test
# #     type: deploy
# #     steps:
# #       - IN: box-man
# #       - IN: env-test
# #       - TASK: managed
# #         deployMethod: upgrade

# #   - name: box-dcl
# #     type: deploy
# #     steps:
# #       - IN: box-man
# #       - IN: env-dcl
# #       - TASK: managed

# #   - name: box-gke
# #     type: deploy
# #     steps:
# #       - IN: box-man
# #       - IN: env-gke
# #       - TASK: managed

# #   - name: box-prod
# #     type: deploy
# #     steps:
# #       - IN: box-man
# #         switch: off
# #       - IN: env-prod
# #       - TASK: managed

# #   - name: multi-manifest
# #     type:  deploy
# #     steps:
# #       - IN: box-man
# #       - IN: dv-man
# #       - IN: env-test
# #       - TASK: managed
# #         deployMethod: upgrade

# #   - name: release-one
# #     type: release
# #     steps:
# #       - IN: version-resource
# #       - IN: dv-man
# #       - TASK: managed
# #         bump: major

# #   - name: box-tripub-man
# #     type: manifest
# #     steps:
# #       - IN: box-image
# #         pull: false
# #       - IN: box-tripub-opts
# #       - TASK: managed

# #   - name: box-tripub
# #     type: deploy
# #     steps:
# #       - IN: box-tripub-man
# #       - IN: env-tripub
# #       - TASK: managed

# #   - name: infra-provision
# #     type: runSh
# #     steps:
# #       - IN: infra-repo
# #       - TASK:
# #         - script: ls
# #         - script: ./GET/infra-repo/infra-repo/provision.sh
# #       - on_success:
# #         - echo 'This block executes after TASK section executes successfully'
# #         - NOTIFY: slackNotifcation
